import './styles.css';
import figlet from 'figlet';

const APP_VERSION = 'v4';
const FALLBACK_LOGO = String.raw`
   ______                __        ____  ___         ___      
  / ____/______  _______/ /_____ _/ /  |/  /__  ____/ (_)___ _
 / /   / ___/ / / / ___/ __/ __ \\ / /|_/ / _ \/ __  / / __ \
/ /___/ /  / /_/ (__  ) /_/ /_/ / / /  / /  __/ /_/ / / /_/ /
\____/_/   \__, /____/\__/\____/_/_/  /_/\___/\__,_/_/\__,_/
          /____/                                             `;

let LOGO = FALLBACK_LOGO;
try { LOGO = figlet.textSync('CrystalMedia', { font: 'Slant' }).replace(/\n+$/, ''); } catch { LOGO = FALLBACK_LOGO; }

class Starfield {
  constructor(cols = 120, rows = 36, count = 220) { this.cols = cols; this.rows = rows; this.count = count; this.resetGeometry(); this.resetAll(); }
  resetGeometry() { this.depth = Math.max(this.cols, this.rows); this.boundsX = Math.max(10, Math.floor(this.cols / 2)); this.boundsY = Math.max(6, Math.floor(this.rows / 2)); }
  resize(cols, rows) { cols = Math.max(30, cols); rows = Math.max(12, rows); if (cols === this.cols && rows === this.rows) return; this.cols = cols; this.rows = rows; this.resetGeometry(); this.resetAll(); }
  newStar(z = rand(1, this.depth)) { const sx = rand(0, this.cols - 1), sy = rand(0, this.rows - 1); return { x: Math.floor(((sx - this.boundsX) * z) / this.boundsX), y: Math.floor(((sy - this.boundsY) * z) / this.boundsY), z, pz: z, speed: [1, 1, 1, 2][rand(0, 3)] }; }
  reset(star) { Object.assign(star, this.newStar(this.depth)); }
  resetAll() { this.stars = Array.from({ length: this.count }, () => this.newStar()); }
  tick() { for (const star of this.stars) { star.pz = star.z; star.z -= star.speed; if (star.z <= 1) this.reset(star); } }
  project(star, z = star.z) { z = Math.max(1, z); return [Math.floor((star.x / z) * this.boundsX + this.boundsX), Math.floor((star.y / z) * this.boundsY + this.boundsY)]; }
  render() { const canvas = Array.from({ length: this.rows }, () => Array(this.cols).fill(' ')); for (const s of this.stars) { const [px, py] = this.project(s, s.pz), [x, y] = this.project(s, s.z); if (inBounds(px, py, this.cols, this.rows)) canvas[py][px] = '.'; if (inBounds(x, y, this.cols, this.rows)) canvas[y][x] = s.z < this.depth / 3 ? '+' : s.z < this.depth / 2 ? '*' : '.'; } return canvas; }
}

const app = document.querySelector('#app');
app.innerHTML = `<main class="termux-shell" aria-label="CrystalMedia browser terminal"><section class="terminal" tabindex="0"><pre id="screen" aria-live="polite"></pre><span class="cursor" aria-hidden="true"></span><input id="hiddenInput" autocomplete="off" spellcheck="false" /></section></main>`;
const screen = document.querySelector('#screen');
const terminal = document.querySelector('.terminal');
const hiddenInput = document.querySelector('#hiddenInput');

let cols = 120, rows = 36, starfield = new Starfield(cols, rows), state = 'menu', selected = 0, lines = [], history = [], histIdx = 0, input = '', progress = null, backend = null;
const categories = ['YouTube Video (MP4)', 'YouTube Music (MP3)', 'Spotify', 'Exit'];
const modes = ['Single Item', 'Playlist'];
const qualities = ['Low (~360p)', 'Medium (~480p–720p)', 'High (~720p–1080p)', 'Best (highest available) [default]'];
const bitrates = ['Low (96 kbps)', 'Medium (128 kbps)', 'Standard (192 kbps) [default]', 'High (256 kbps)', 'Insane (320 kbps)'];
let flow = { category: null, mode: null, url: '', extras: true, quality: '', bitrate: '192' };

function rand(a, b) { return Math.floor(Math.random() * (b - a + 1)) + a; }
function inBounds(x, y, w, h) { return x >= 0 && y >= 0 && x < w && y < h; }
function activeOptions() { return state === 'menu' ? categories : state === 'mode' ? modes : state === 'extras' ? ['Yes (recommended for MP3)', 'No'] : flow.category === 'YouTube Music (MP3)' ? bitrates : qualities; }
function measure() { const style = getComputedStyle(screen); const charW = parseFloat(style.fontSize) * 0.61; const charH = parseFloat(style.lineHeight); cols = Math.max(60, Math.floor(terminal.clientWidth / charW)); rows = Math.max(18, Math.floor(terminal.clientHeight / charH)); starfield.resize(cols, rows); }
function overlay(canvas, text, r = 2, c = 2) { text.split('\n').forEach((line, i) => { const y = r + i; if (y >= canvas.length) return; for (let x = 0; x < line.length && c + x < cols; x++) if (line[x] !== ' ') canvas[y][c + x] = line[x]; }); }
function baseCanvas(body = '') { const canvas = starfield.render(); overlay(canvas, LOGO, 3, 2); overlay(canvas, `${APP_VERSION}\n${'-'.repeat(Math.min(cols - 4, 60))}`, 3 + LOGO.split('\n').length, 2); if (body) overlay(canvas, body, 5 + LOGO.split('\n').length, 2); return canvas.map(r => r.join('')).join('\n'); }
function menuBody(title, opts, help = '↑ ↓ to navigate • Enter to select • Ctrl+C to quit') { return [title, ...opts.map((o, i) => (i === selected ? '→ ' : '  ') + o), '', help].join('\n'); }
function render() { starfield.tick(); if (state === 'menu') screen.textContent = baseCanvas(menuBody('Main Category Selection', categories)); else if (state === 'mode') screen.textContent = baseCanvas(menuBody('Mode Selection', modes)); else if (state === 'quality') screen.textContent = baseCanvas(menuBody(flow.category === 'YouTube Music (MP3)' ? 'MP3 Bitrate Selection' : 'MP4 Quality Selection', activeOptions())); else if (state === 'extras') screen.textContent = baseCanvas(menuBody('Embed extras (lyrics + art + subtitle fallback + metadata)', activeOptions())); else if (state === 'input') screen.textContent = baseCanvas(`\nResource URL → ${input}\n\nType URL • Backspace to edit • Enter to continue • Ctrl+C to cancel`); else if (state === 'progress') screen.textContent = renderProgress(); else if (state === 'shell') screen.textContent = baseCanvas(lines.slice(-Math.max(1, rows - 10)).join('\n') + `\n\ncrystalmedia@web:~$ ${input}`); }
function renderProgress() { const pct = progress?.pct ?? 0; const barWidth = Math.min(48, cols - 30); const fill = Math.round((pct / 100) * barWidth); const bar = '█'.repeat(fill) + '░'.repeat(barWidth - fill); const logLines = (progress?.logs || []).slice(-12).join('\n'); const files = (progress?.files || []).map(f => `Download ready: ${f.url}`).join('\n'); return baseCanvas(`Downloading: ${flow.url || 'waiting'}\nMode: ${flow.mode} ${flow.category}\nOutput: CrystalMedia_output/downloads (server)\n\n╭─ Progress ─────────────────────────────────╮\n│ ${progress?.desc || 'Waiting'} ${bar} ${String(Math.round(pct)).padStart(3)}% │\n╰─────────────────────────────────────────────╯\n\n╭─ Download Log ──────────────────────────────╮\n${logLines}\n${files}\n╰─────────────────────────────────────────────╯`); }
async function checkBackend() { try { const res = await fetch('/api/status'); backend = await res.json(); lines.push(`Backend connected: yt-dlp=${backend.ytDlp} ffmpeg=${backend.ffmpeg}`); } catch { backend = null; lines.push('Static mode: start the Node backend with npm run server for native yt-dlp downloads.'); } }
async function startDownload() { state = 'progress'; progress = { pct: 0, desc: 'Starting yt-dlp', logs: ['[info] submitting native yt-dlp job to backend...'], files: [] }; try { const res = await fetch('/api/download', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(flow) }); const payload = await res.json(); if (!res.ok) throw new Error(payload.error || 'backend rejected job'); const events = new EventSource(`/api/events/${payload.id}`); events.onmessage = (event) => { const data = JSON.parse(event.data); progress = { pct: data.pct, desc: data.status === 'running' ? 'Downloading' : data.status, logs: data.logs, files: data.files }; if (data.status !== 'running') { events.close(); setTimeout(() => { state = 'shell'; lines.push(data.status === 'complete' ? 'Download complete. File link is shown in the progress log.' : 'Download failed. Review yt-dlp output above.'); }, 2200); } }; events.onerror = () => { progress.logs.push('[error] lost backend event stream'); events.close(); }; } catch (err) { progress = { pct: 0, desc: 'Backend unavailable', logs: [`[error] ${err.message}`, '[hint] Run npm run server on a host with yt-dlp and ffmpeg installed.'], files: [] }; } }
function submitCommand(cmd) { if (!cmd.trim()) return; history.push(cmd); histIdx = history.length; lines.push(`crystalmedia@web:~$ ${cmd}`); const [name, ...args] = cmd.trim().split(/\s+/); const table = { help: helpText, compat: compatText, deps: depsText, exportify: exportifyText, clear: () => { lines = []; return ''; }, menu: () => { state = 'menu'; selected = 0; return 'Returning to main menu.'; }, youtube: () => { flow.category = 'YouTube Video (MP4)'; state = 'mode'; selected = 0; return 'YouTube Video flow opened.'; }, music: () => { flow.category = 'YouTube Music (MP3)'; state = 'mode'; selected = 0; return 'YouTube Music flow opened.'; }, spotify: () => { flow.category = 'Spotify'; state = 'mode'; selected = 0; return 'Spotify flow opened.'; }, backend: () => JSON.stringify(backend, null, 2), open: () => { if (args[0]) window.open(args[0], '_blank', 'noopener'); return `Opened ${args[0] || 'nothing'}`; } }; const out = (table[name] || (() => `Unknown command: ${name}. Try help.`))(); if (out) out.split('\n').forEach(l => lines.push(l)); input = ''; }
function helpText() { return `Commands: help, menu, youtube, music, spotify, exportify, compat, deps, backend, open <url>, clear\nKeyboard: ↑/↓ navigate menus, Enter select, Ctrl+C returns to menu.\nURL input is fully editable in the Resource URL area.`; }
function compatText() { return `Feature compatibility report:\n- Full native yt-dlp is available when the included Node backend is running.\n- The frontend streams real yt-dlp stdout/stderr and parses live percent progress.\n- Static-only hosts can show the replica UI but cannot spawn yt-dlp processes.\n- Browser-prohibited global hooks/cookie scraping are replaced by focused terminal input and server-side yt-dlp options.`; }
function depsText() { return `Dependency migration table:\nrich/Live -> terminal renderer + CSS panels\npyfiglet -> figlet npm Slant FIGlet rendering\nyt-dlp -> included Node backend spawning native yt-dlp\nffmpeg -> native ffmpeg beside yt-dlp on backend\nspotdl -> Spotify search/Exportify CSV flow through yt-dlp\nmutagen -> yt-dlp --embed-metadata/--embed-thumbnail where supported`; }
function exportifyText() { return `Exportify integration:\n1. Open https://watsonbox.github.io/exportify/ with: open https://watsonbox.github.io/exportify/\n2. Export playlist CSV and paste each Track + Artist into Spotify mode, or post CSV to /api/exportify/parse.\n3. Spotify mode sends metadata queries into yt-dlp as ytsearch1:<track artist>.`; }
function key(e) { terminal.focus(); hiddenInput.focus(); if (e.ctrlKey && e.key.toLowerCase() === 'c') { state = 'menu'; selected = 0; input = ''; e.preventDefault(); return; } if (['menu', 'mode', 'quality', 'extras'].includes(state)) { const opts = activeOptions(); if (e.key === 'ArrowUp') { selected = (selected - 1 + opts.length) % opts.length; e.preventDefault(); } if (e.key === 'ArrowDown') { selected = (selected + 1) % opts.length; e.preventDefault(); } if (e.key === 'Enter') { choose(); e.preventDefault(); } return; } if (state === 'input' || state === 'shell') { if (e.key === 'Enter') { state === 'input' ? (flow.url = input, input = '', selected = 0, state = 'extras') : submitCommand(input); e.preventDefault(); } else if (e.key === 'Backspace') { input = input.slice(0, -1); e.preventDefault(); } else if (e.key === 'ArrowUp' && state === 'shell') { histIdx = Math.max(0, histIdx - 1); input = history[histIdx] || ''; e.preventDefault(); } else if (e.key === 'ArrowDown' && state === 'shell') { histIdx = Math.min(history.length, histIdx + 1); input = history[histIdx] || ''; e.preventDefault(); } else if (e.key.length === 1 && !e.metaKey && !e.ctrlKey) { input += e.key; e.preventDefault(); } } }
function choose() { if (state === 'menu') { if (selected === 3) { state = 'shell'; lines.push('Thank you for using CrystalMedia Web.'); return; } flow.category = categories[selected]; selected = 0; state = 'mode'; } else if (state === 'mode') { flow.mode = modes[selected]; input = ''; state = 'input'; } else if (state === 'extras') { flow.extras = selected === 0; selected = 0; if (flow.category === 'Spotify') startDownload(); else state = 'quality'; } else if (state === 'quality') { const picked = activeOptions()[selected]; if (flow.category === 'YouTube Music (MP3)') flow.bitrate = picked.match(/(\d+)/)?.[1] || '192'; else flow.quality = picked; startDownload(); } }

document.addEventListener('keydown', key); window.addEventListener('resize', measure); terminal.addEventListener('click', () => hiddenInput.focus()); measure(); checkBackend(); setInterval(render, 1000 / 30); lines.push('CrystalMedia Web terminal ready. Type help or use ↑/↓/Enter.');
